"""Add name column to Task table

Revision ID: 23596d9f598f
Revises: 48c50ba7819c
Create Date: 2022-10-13 17:02:02.042390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23596d9f598f'
down_revision = '48c50ba7819c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('employee', sa.Column('password', sa.String(length=60), nullable=False))
    op.add_column('task', sa.Column('name', sa.String(length=30), server_default='pre table migration', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'name')
    op.drop_column('employee', 'password')
    op.drop_column('employee', 'email')
    # ### end Alembic commands ###
