"""Add name column to Task table

Revision ID: 87152264da45
Revises: e22523f40760
Create Date: 2022-10-13 17:16:21.225073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87152264da45'
down_revision = 'e22523f40760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('employee', sa.Column('password', sa.String(length=60), nullable=False))
    op.add_column('task', sa.Column('name', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'name')
    op.drop_column('employee', 'password')
    op.drop_column('employee', 'email')
    # ### end Alembic commands ###
