"""Initial Migration

Revision ID: a31d72e57c21
Revises: 
Create Date: 2022-10-13 16:31:47.683675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31d72e57c21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('employee', sa.Column('password', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'password')
    op.drop_column('employee', 'email')
    # ### end Alembic commands ###
